[package]
name = "partymod"
version = "2.0.0-preview01"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
libc = "0.2"
windows-core = "0.62.2"
sdl3 = { version = "0.17.3", features = ["build-from-source", "raw-window-handle"] }
raw-window-handle = "0.6.2"
partymod-common = { git = "https://github.com/PARTYMANX/partymod-common" }
partymod-config-common = { git = "https://github.com/PARTYMANX/partymod-common" }
partymod-config = { path = "../partymod-config" }

[dependencies.windows]
version = "0.62.2"
features = [
    "Win32",
    "Win32_System",
    "Win32_System_Threading",
    "Win32_System_Memory",
    "Win32_System_SystemServices",
    "Win32_System_Console",
    "Win32_System_WindowsProgramming",
    "Win32_System_Com",
    "Win32_Media",
    "Win32_Media_MediaFoundation",
    "Win32_Graphics",
    "Win32_Graphics_Imaging",
]

[dependencies.windows-sys]
version = "0.61.2"
features = [
    "Win32",
    "Win32_System",
    "Win32_System_Memory",
    "Win32_System_SystemServices",
    "Win32_System_Console",
    "Win32_System_WindowsProgramming",
]

[build-dependencies]
cc = "1.2.50"
