[package]
name = "partymod-common"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
sdl3 = { version = "0.17.3", features = ["build-from-source", "raw-window-handle"] }
partymod-config-common = { path = "../partymod-config-common" }

[dependencies.windows-sys]
version = "0.61.2"
features = [
    "Win32",
    "Win32_System",
    "Win32_System_Memory",
    "Win32_System_SystemServices",
    "Win32_System_Console",
    "Win32_System_WindowsProgramming",
    "Win32_UI",
    "Win32_UI_HiDpi",
]

[build-dependencies]
cc = "1.2.50"
