[package]
name = "pgui"
version = "2.0.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.windows]
version = "0.62.2"
features = [
    "Win32",
    "Win32_System",
    "Win32_System_LibraryLoader",
    "Win32_System_Memory",
    "Win32_System_SystemServices",
    "Win32_System_Console",
    "Win32_System_WindowsProgramming",
    "Win32_Graphics_Gdi", "Win32_UI",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Controls",
    "Win32_UI_Shell",
    "Win32_UI_HiDpi",
    "Win32_UI_Input_KeyboardAndMouse",
]

[build-dependencies]
embed-resource = "3.0"
