[package]
name = "partyconfig"
version = "2.0.0"
edition = "2024"

[dependencies]
sdl3 = { version = "0.17.3", features = ["build-from-source", "raw-window-handle"] }
pgui = { path = "../pgui" }

[dependencies.windows]
version = "0.62.2"
features = [
    "Win32_Graphics_Gdi",
    "Win32_System_WindowsProgramming",
]
